"""36_drop_deletion_scheduled_for_from_users

Revision ID: 1b4e046103bf
Revises: 53c8e23b05f7
Create Date: 2026-08-16 10:35:27.945182

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b4e046103bf"
down_revision: str | Sequence[str] | None = "53c8e23b05f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deletion_scheduled_for")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "deletion_scheduled_for", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###
