"""28_drop_student_guardian_links_table

Revision ID: 1d8094827b5b
Revises: 9a9ba48ec6c9
Create Date: 2026-08-16 08:34:09.954958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d8094827b5b"
down_revision: str | Sequence[str] | None = "9a9ba48ec6c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uix_one_primary_guardian_per_student"),
        table_name="student_guardian_links",
        postgresql_where="(priority = 'PRIMARY'::guardianpriority)",
    )
    op.drop_index(
        op.f("uix_one_secondary_guardian_per_student"),
        table_name="student_guardian_links",
        postgresql_where="(priority = 'SECONDARY'::guardianpriority)",
    )
    op.drop_table("student_guardian_links")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_guardian_links",
        sa.Column("guardian_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "priority",
            postgresql.ENUM("PRIMARY", "SECONDARY", name="guardianpriority"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["users.id"],
            name=op.f("student_guardian_links_guardian_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("student_guardian_links_student_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("student_guardian_links_pkey")),
        sa.UniqueConstraint(
            "guardian_id",
            "student_id",
            name=op.f("uix_guardian_student_pair"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("uix_one_secondary_guardian_per_student"),
        "student_guardian_links",
        ["student_id"],
        unique=True,
        postgresql_where="(priority = 'SECONDARY'::guardianpriority)",
    )
    op.create_index(
        op.f("uix_one_primary_guardian_per_student"),
        "student_guardian_links",
        ["student_id"],
        unique=True,
        postgresql_where="(priority = 'PRIMARY'::guardianpriority)",
    )
    # ### end Alembic commands ###
