"""add unique constraint to student_group

Revision ID: 2cfc87ab938b
Revises: b77299ddc86c
Create Date: 2026-03-11 20:59:48.292024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfc87ab938b'
down_revision: Union[str, Sequence[str], None] = 'b77299ddc86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_student_group', 'student_group', ['student_id', 'group_id', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_student_group', 'student_group', type_='unique')
    # ### end Alembic commands ###
