"""07_add_new_value_to_userstatus_enum

Revision ID: 3985049ef40a
Revises: bdb2a6244370
Create Date: 2026-06-26 10:07:03.598121

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3985049ef40a"
down_revision: Union[str, Sequence[str], None] = "bdb2a6244370"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userstatus ADD VALUE 'PENDING_ACTIVATION'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
