"""add mark_ type column to marks with column type enum

Revision ID: 65ba71ee0d49
Revises: 723078428f07
Create Date: 2026-03-09 18:02:35.654372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ba71ee0d49'
down_revision: Union[str, Sequence[str], None] = '723078428f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('mark_type', sa.Enum('regular_mark', 'regular_exam', 'midterm_exam', 'final_exam', name='marktype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'mark_type')
    # ### end Alembic commands ###