"""08_delete_user_login_lockout_fields_from_user_session

Revision ID: 68a3811de34b
Revises: 3985049ef40a
Create Date: 2026-06-26 11:49:24.250338

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68a3811de34b"
down_revision: Union[str, Sequence[str], None] = "3985049ef40a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_sessions", "failed_login_attempts")
    op.drop_column("users_sessions", "locked_until")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_sessions",
        sa.Column(
            "locked_until",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users_sessions",
        sa.Column(
            "failed_login_attempts", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
