"""33_drop_head_of_class_assignments_table

Revision ID: 7028c00cfe11
Revises: dfe282f48297
Create Date: 2026-08-16 09:17:07.617138

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7028c00cfe11"
down_revision: str | Sequence[str] | None = "dfe282f48297"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("head_of_class_assignments")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "head_of_class_assignments",
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("PRIMARY", "DEPUTY", name="headofclassrole"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("head_of_class_assignments_group_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("head_of_class_assignments_teacher_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("head_of_class_assignments_pkey")),
        sa.UniqueConstraint(
            "group_id",
            "role",
            name=op.f("uix_head_of_class_role_per_group"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "teacher_id",
            "group_id",
            name=op.f("uix_head_of_class_teacher_per_group"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
