"""drop subjects title unique constraint

Revision ID: 723078428f07
Revises: d286ffdf4e18
Create Date: 2026-03-09 17:53:48.994983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723078428f07'
down_revision: Union[str, Sequence[str], None] = 'd286ffdf4e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subjects_title_key'), 'subjects', type_='unique')
    op.create_unique_constraint('uix_title_language', 'subjects', ['title', 'language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_title_language', 'subjects', type_='unique')
    op.create_unique_constraint(op.f('subjects_title_key'), 'subjects', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###