"""11_add_deletion_scheduled_for_field_to_users_table

Revision ID: 7b5f823fdbb2
Revises: fdc2e3dc5741
Create Date: 2026-07-01 12:02:47.444291

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b5f823fdbb2"
down_revision: str | Sequence[str] | None = "fdc2e3dc5741"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("deletion_scheduled_for", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deletion_scheduled_for")
    # ### end Alembic commands ###
