"""01_create_users_table

Revision ID: 949a91ac7cfb
Revises:
Create Date: 2026-06-20 15:08:39.398912

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "949a91ac7cfb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("firstname", sa.String(length=50), nullable=False),
        sa.Column("lastname", sa.String(length=50), nullable=False),
        sa.Column("middlename", sa.String(length=50), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("phone_number", sa.String(length=25), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM_ADMIN",
                "DIRECTOR",
                "VICE_DIRECTOR",
                "TEACHER",
                "STUDENT",
                "PARENT",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "GRADUATED", "EXPELLED", "WITHDRAWN", name="userstatus"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, default=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number", "email", "role", name="uix_parent_fields"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_firstname"), "users", ["firstname"], unique=False)
    op.create_index(op.f("ix_users_lastname"), "users", ["lastname"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_lastname"), table_name="users")
    op.drop_index(op.f("ix_users_firstname"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
