"""04_add_new_values_to_userstatus_enum

Revision ID: 950157153063
Revises: c639e4958798
Create Date: 2026-06-24 22:48:08.701292

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "950157153063"
down_revision: Union[str, Sequence[str], None] = "c639e4958798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userstatus ADD VALUE 'DEACTIVATED'")
    op.execute("ALTER TYPE userstatus ADD VALUE 'PENDING_DELETION'")
    op.execute("ALTER TYPE userstatus ADD VALUE 'DELETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
