"""23_create_groups_table

Revision ID: 96e8a97a059e
Revises: 4ab31d3f8f07
Create Date: 2026-07-15 11:06:34.290658

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96e8a97a059e"
down_revision: str | Sequence[str] | None = "4ab31d3f8f07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("academic_year", sa.Integer(), nullable=False),
        sa.Column("grade_level", sa.Integer(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "academic_year", name="uix_group_name_academic_year"
        ),
    )
    op.create_index(
        op.f("ix_groups_academic_year"), "groups", ["academic_year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_groups_academic_year"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
