"""27_add_group_id_field_to_users_table

Revision ID: 9a9ba48ec6c9
Revises: 2da33bf49ce7
Create Date: 2026-07-15 11:31:44.145287

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a9ba48ec6c9"
down_revision: str | Sequence[str] | None = "2da33bf49ce7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_group_id"), "users", ["group_id"], unique=False)
    op.create_foreign_key(None, "users", "groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_group_id"), table_name="users")
    op.drop_column("users", "group_id")
    # ### end Alembic commands ###
