"""19_create_student_guardian_table

Revision ID: 9b8e1ca4bb22
Revises: 7046ab92b402
Create Date: 2026-07-13 21:50:24.232385

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b8e1ca4bb22"
down_revision: str | Sequence[str] | None = "7046ab92b402"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_guardian_links",
        sa.Column("guardian_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("PRIMARY", "SECONDARY", name="guardianpriority"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["guardian_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guardian_id", "student_id", name="uix_guardian_student_pair"
        ),
    )
    op.create_index(
        "uix_one_primary_guardian_per_student",
        "student_guardian_links",
        ["student_id"],
        unique=True,
        postgresql_where=sa.text("priority = 'PRIMARY'"),
    )
    op.create_index(
        "uix_one_secondary_guardian_per_student",
        "student_guardian_links",
        ["student_id"],
        unique=True,
        postgresql_where=sa.text("priority = 'SECONDARY'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_one_secondary_guardian_per_student",
        table_name="student_guardian_links",
        postgresql_where=sa.text("priority = 'SECONDARY'"),
    )
    op.drop_index(
        "uix_one_primary_guardian_per_student",
        table_name="student_guardian_links",
        postgresql_where=sa.text("priority = 'PRIMARY'"),
    )
    op.drop_table("student_guardian_links")
    # ### end Alembic commands ###
