"""19_create_student_guardian_table

Revision ID: 9b8e1ca4bb22
Revises: 7046ab92b402
Create Date: 2026-07-13 21:50:24.232385

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9b8e1ca4bb22"
down_revision: str | Sequence[str] | None = "7046ab92b402"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
