"""31_drop_teaching_assignments_table

Revision ID: a8eefcee60d1
Revises: 398ace688b6f
Create Date: 2026-08-16 09:06:29.871916

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8eefcee60d1"
down_revision: str | Sequence[str] | None = "398ace688b6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teaching_assignments")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teaching_assignments",
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("subject_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("teaching_assignments_group_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("teaching_assignments_subject_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("teaching_assignments_teacher_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("teaching_assignments_pkey")),
        sa.UniqueConstraint(
            "teacher_id",
            "subject_id",
            "group_id",
            name=op.f("uix_teaching_assignment"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
