"""02_create_user_session_and_activation_tables

Revision ID: b117acf58e78
Revises: 949a91ac7cfb
Create Date: 2026-06-22 21:19:43.489332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b117acf58e78"
down_revision: str | Sequence[str] | None = "949a91ac7cfb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_activations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("invite_token_hash", sa.String(), nullable=True),
        sa.Column("invite_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "users_sessions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_token_version", sa.Integer(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(), nullable=True),
        sa.Column(
            "refresh_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("refresh_token_family", sa.String(length=64), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reset_password_token_hash", sa.String(), nullable=True),
        sa.Column(
            "reset_password_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("pending_new_email", sa.String(length=100), nullable=True),
        sa.Column("email_change_code_hash", sa.String(), nullable=True),
        sa.Column(
            "email_change_code_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_sessions")
    op.drop_table("users_activations")
    # ### end Alembic commands ###
