"""add status column to studentsubject with enum

Revision ID: b19f2f70c04e
Revises: c3ff619a67ca
Create Date: 2026-03-10 08:08:44.339000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19f2f70c04e'
down_revision: Union[str, Sequence[str], None] = 'c3ff619a67ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject', sa.Column('status', sa.Enum('finished', 'withdrawn', 'studying', name='studentsubjectstatus'), nullable=False))
    op.add_column('student_subject', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uix_student_subject', 'student_subject', ['student_id', 'subject_id', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_student_subject', 'student_subject', type_='unique')
    op.drop_column('student_subject', 'updated_at')
    op.drop_column('student_subject', 'status')
    # ### end Alembic commands ###
