"""03_create_users_login_lockout_table

Revision ID: c639e4958798
Revises: b117acf58e78
Create Date: 2026-06-24 22:20:57.716116

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c639e4958798"
down_revision: str | Sequence[str] | None = "b117acf58e78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_login_lockout",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.alter_column("users", "created_by", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("uix_parent_fields"), "users", type_="unique")
    op.create_index(
        "uix_non_student_unique_contact",
        "users",
        ["phone_number", "email"],
        unique=True,
        postgresql_where=sa.text("role <> 'STUDENT'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_non_student_unique_contact",
        table_name="users",
        postgresql_where=sa.text("role <> 'student'"),
    )
    op.create_unique_constraint(
        op.f("uix_parent_fields"),
        "users",
        ["phone_number", "email", "role"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("users", "created_by", existing_type=sa.INTEGER(), nullable=False)
    op.drop_table("users_login_lockout")
    # ### end Alembic commands ###
