"""29_drop_grades_comments_table

Revision ID: d2134ebd6684
Revises: 1d8094827b5b
Create Date: 2026-08-16 08:39:03.108925

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2134ebd6684"
down_revision: str | Sequence[str] | None = "1d8094827b5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grade_comments")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grade_comments",
        sa.Column("grade_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("author_public_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "author_display_name",
            sa.VARCHAR(length=101),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "content", sa.VARCHAR(length=1000), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("grade_comments_author_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["grades.id"],
            name=op.f("grade_comments_grade_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("grade_comments_pkey")),
    )
    # ### end Alembic commands ###
