"""16_create_corrected_partial_indexes_for_users_table

Revision ID: d39b1ad84cc2
Revises: 4ff88a821ec8
Create Date: 2026-07-12 12:00:24.677665

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd39b1ad84cc2'
down_revision: Union[str, Sequence[str], None] = '4ff88a821ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_non_student_unique_contact", table_name="users")
    op.create_index(
        "uix_non_student_unique_phone",
        "users",
        ["phone_number"],
        unique=True,
        postgresql_where=sa.text("role <> 'STUDENT'"),
    )
    op.create_index(
        "uix_non_student_unique_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("role <> 'STUDENT'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_non_student_unique_phone", table_name="users")
    op.drop_index("uix_non_student_unique_email", table_name="users")
    op.create_index(
        "uix_non_student_unique_contact",
        "users",
        ["phone_number", "email"],
        unique=True,
        postgresql_where=sa.text("role <> 'STUDENT'"),
    )
    # ### end Alembic commands ###
