"""32_drop_student_subject_enrollments_table

Revision ID: dfe282f48297
Revises: a8eefcee60d1
Create Date: 2026-08-16 09:11:44.779005

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfe282f48297"
down_revision: str | Sequence[str] | None = "a8eefcee60d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_subject_enrollments")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_subject_enrollments",
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("subject_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("student_subject_enrollments_group_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("student_subject_enrollments_student_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("student_subject_enrollments_subject_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("student_subject_enrollments_pkey")),
        sa.UniqueConstraint(
            "student_id",
            "subject_id",
            "group_id",
            name=op.f("uix_student_subject_enrollment"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
