"""05_make_date_of_birth_field_nullable

Revision ID: e663588b368d
Revises: 950157153063
Create Date: 2026-06-25 08:49:58.058009

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e663588b368d'
down_revision: Union[str, Sequence[str], None] = '950157153063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth', existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth', existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
