"""10_create_pending_emails_table

Revision ID: fdc2e3dc5741
Revises: 3d688dc43847
Create Date: 2026-06-26 19:40:00.500448

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdc2e3dc5741"
down_revision: Union[str, Sequence[str], None] = "3d688dc43847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_emails",
        sa.Column("recipient", sa.String(length=100), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("html_body", sa.Text(), nullable=False),
        sa.Column("text_body", sa.Text(), nullable=False),
        sa.Column(
            "email_type",
            sa.Enum(
                "INVITE",
                "PASSWORD_RESET_ADMIN",
                "ACTIVATION_WITH_TOKEN",
                "ACCOUNT_DEACTIVATION",
                "ACCOUNT_ACTIVATION",
                name="emailtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="emailsendingstatus"),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.Column("recipient_user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pending_emails_recipient_user_id"),
        "pending_emails",
        ["recipient_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_emails_status"), "pending_emails", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pending_emails_triggered_by"),
        "pending_emails",
        ["triggered_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_emails_triggered_by"), table_name="pending_emails")
    op.drop_index(op.f("ix_pending_emails_status"), table_name="pending_emails")
    op.drop_index(
        op.f("ix_pending_emails_recipient_user_id"), table_name="pending_emails"
    )
    op.drop_table("pending_emails")
    # ### end Alembic commands ###
